apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mirador-rca.fullname" . }}-config
  labels:
    {{- include "mirador-rca.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := .Values.config -}}
    {{- if .Values.vllm.enabled -}}
    {{- $_ := set $config.llm "enabled" true -}}
    {{- end -}}
    {{- toYaml $config | nindent 4 }}
